# following xgcm ci environment specs
name: test_env_ecco
channels:
  - conda-forge
dependencies:
  - python=3.7
  - xarray
  - dask
  - numpy
  - scipy
  - pytest
  - future
  - xgcm>=0.5.0
  - pytest 
  - codecov
  - pytest-cov
  - pyresample
  - cartopy
  - docrep
  - fsspec
  - aiohttp
  - pip
  - pip:
      - git+https://github.com/MITgcm/xmitgcm.git
