# following xgcm ci environment specs
name: test_env_ecco
channels:
  - conda-forge
dependencies:
  - aiohttp
  - codecov
  - cartopy>=0.18.0
  - cmocean
  - dask
  - docrep
  - fsspec
  - future
  - geos
  - matplotlib
  - netcdf4
  - numpy
  - pathlib
  - proj
  - pytest
  - python=3.8
  - pytest-cov
  - pyresample
  - scipy
  - xarray
  - xgcm>=0.5.0
  - xmitgcm>=0.5.1
